### ISSUE TITLE
Clarify situation for slider

### ISSUE THREAD

**Issue by courtiol** [courtiol/lay#7]
I am not sure why but slider (and only slider) shows very different speed whenever run in README vs in the vignette showing the benchmarks:

Vignette:
![image](https://user-images.githubusercontent.com/7499666/99916659-afaa5d00-2d0b-11eb-94ed-692cf86de55e.png)

README:
![image](https://user-images.githubusercontent.com/7499666/99916684-c8b30e00-2d0b-11eb-84c6-32fb1827387a.png)

@DavisVaughan, any idea why? I only discovered your great package right now and did not dig, but this is quite intriguing... Is it a compilation issue?

**Comment by DavisVaughan** [comment]
Typo? drugs->drugs_full?

**Comment by DavisVaughan** [comment]
https://github.com/courtiol/lay/blob/5f4dc11a382984b39b65b6d44dae60f3fbe555fe/README.Rmd#L286

**Comment by courtiol** [comment]
I thought I had checked that 50 times, but I guess I was getting tired... sorry :-/ and THANKS!
